import type { StoreConfig } from "@/lib/store-types";

/** Demo configuration: replace or load per-tenant in production */
export const defaultStoreConfig: StoreConfig = {
  brand: {
    monogram: "RS",
    name: "Ruedas y Soluciones",
    tagline: "Tu confianza en nuestras manos",
    logoUrl: null,
    homeHref: "/",
  },
  navLinks: [],
  contact: {
    title: "Entra en contacto",
    lines: [
      {
        icon: "whatsapp",
        label: "+57 300 000 0000",
        href: "https://wa.me/573000000000",
      },
      { icon: "phone", label: "+57 (601) 000 0000", href: "tel:+576010000000" },
      {
        icon: "location",
        label: "Calle 00 #00-00, Bogotá",
      },
    ],
  },
  pickup: {
    title: "Recogida",
    deliveryLabel: "Entrega",
    pickupLabel: "Recogida",
    options: [
      {
        id: "local-a",
        label: "Punto A — Centro",
        address: "Calle 00 #00-00",
      },
      {
        id: "local-b",
        label: "Punto B — Norte",
        address: "Carrera 00 #00-00",
      },
    ],
  },
  catalog: {
    eyebrow: "Tienda online",
    headline: "Todo lo que buscas, en un solo lugar",
    subline:
      "Navega por nuestros productos, compara y elige con calma. Compra de forma rápida y segura; estamos aquí para ayudarte cuando lo necesites.",
    sortLabel: "Más relevante",
    sortOptions: [
      { id: "relevant", label: "Más relevante" },
      { id: "price-asc", label: "Menor precio" },
      { id: "price-desc", label: "Mayor precio" },
    ],
    products: [
      {
        id: "1",
        title: "Neumático touring 195/65 R15 91H",
        imageSrc: "https://picsum.photos/seed/rs-p1/400/400",
        imageAlt: "Neumático touring",
        price: 289000,
        currencySymbol: "$",
        ref: "SKU-TYR-195651591H",
        description:
          "Neumático touring para uso urbano y carretera. Buen equilibrio entre confort, duración y consumo. Verifica compatibilidad con tu vehículo antes de comprar.",
      },
      {
        id: "2",
        title: "Neumático SUV 225/60 R17 99V",
        imageSrc: "https://picsum.photos/seed/rs-p2/400/400",
        imageAlt: "Neumático SUV",
        price: 425000,
        currencySymbol: "$",
      },
      {
        id: "3",
        title: 'Llanta de aleación 16" 5×114.3 grafito',
        imageSrc: "https://picsum.photos/seed/rs-p3/400/400",
        imageAlt: "Llanta de aleación",
        price: 512000,
        currencySymbol: "$",
      },
      {
        id: "4",
        title: 'Llanta de acero 15" con tapón',
        imageSrc: "https://picsum.photos/seed/rs-p4/400/400",
        imageAlt: "Llanta de acero",
        price: 198000,
        currencySymbol: "$",
      },
      {
        id: "5",
        title: "Kit sensores TPMS (4 unidades)",
        imageSrc: "https://picsum.photos/seed/rs-p5/400/400",
        imageAlt: "Sensores TPMS",
        price: 156000,
        currencySymbol: "$",
      },
      {
        id: "6",
        title: "Cadena de nieve textil talla M",
        imageSrc: "https://picsum.photos/seed/rs-p6/400/400",
        imageAlt: "Cadenas de nieve",
        price: 89000,
        currencySymbol: "$",
      },
      {
        id: "7",
        title: "Compresor portátil 12V digital",
        imageSrc: "https://picsum.photos/seed/rs-p7/400/400",
        imageAlt: "Compresor portátil",
        price: 124000,
        currencySymbol: "$",
      },
      {
        id: "8",
        title: "Kit reparación pinchazos emergencia",
        imageSrc: "https://picsum.photos/seed/rs-p8/400/400",
        imageAlt: "Kit reparación pinchazos",
        price: 45900,
        currencySymbol: "$",
      },
      {
        id: "9",
        title: "Aceite motor sintético 5W-30 4 L",
        imageSrc: "https://picsum.photos/seed/rs-p9/400/400",
        imageAlt: "Aceite motor",
        price: 98500,
        currencySymbol: "$",
      },
      {
        id: "10",
        title: "Filtro de aceite cartucho universal",
        imageSrc: "https://picsum.photos/seed/rs-p10/400/400",
        imageAlt: "Filtro de aceite",
        price: 22800,
        currencySymbol: "$",
      },
      {
        id: "11",
        title: "Pastillas de freno delanteras cerámicas",
        imageSrc: "https://picsum.photos/seed/rs-p11/400/400",
        imageAlt: "Pastillas de freno",
        price: 178000,
        currencySymbol: "$",
      },
      {
        id: "12",
        title: "Discos de freno ventilados par",
        imageSrc: "https://picsum.photos/seed/rs-p12/400/400",
        imageAlt: "Discos de freno",
        price: 265000,
        currencySymbol: "$",
      },
      {
        id: "13",
        title: "Batería 12V 60 Ah 540 A arranque",
        imageSrc: "https://picsum.photos/seed/rs-p13/400/400",
        imageAlt: "Batería automotriz",
        price: 342000,
        currencySymbol: "$",
      },
      {
        id: "14",
        title: 'Escobillas limpiaparabrisas 24" / 18"',
        imageSrc: "https://picsum.photos/seed/rs-p14/400/400",
        imageAlt: "Escobillas limpiaparabrisas",
        price: 38900,
        currencySymbol: "$",
      },
      {
        id: "15",
        title: "Líquido refrigerante concentrado 1 L",
        imageSrc: "https://picsum.photos/seed/rs-p15/400/400",
        imageAlt: "Refrigerante",
        price: 24900,
        currencySymbol: "$",
      },
      {
        id: "16",
        title: "Alfombras de goma a medida juego 4",
        imageSrc: "https://picsum.photos/seed/rs-p16/400/400",
        imageAlt: "Alfombras de goma",
        price: 112000,
        currencySymbol: "$",
      },
      {
        id: "17",
        title: "Portaequipajes de techo barras aluminio",
        imageSrc: "https://picsum.photos/seed/rs-p17/400/400",
        imageAlt: "Portaequipajes",
        price: 389000,
        currencySymbol: "$",
      },
      {
        id: "18",
        title: "Cámara de reversa HD con guías",
        imageSrc: "https://picsum.photos/seed/rs-p18/400/400",
        imageAlt: "Cámara de reversa",
        price: 95000,
        currencySymbol: "$",
      },
      {
        id: "19",
        title: "Cargador USB-C + USB doble 12V",
        imageSrc: "https://picsum.photos/seed/rs-p19/400/400",
        imageAlt: "Cargador coche",
        price: 31500,
        currencySymbol: "$",
      },
      {
        id: "20",
        title: "Organizador maletero plegable",
        imageSrc: "https://picsum.photos/seed/rs-p20/400/400",
        imageAlt: "Organizador maletero",
        price: 67900,
        currencySymbol: "$",
      },
      {
        id: "21",
        title: "Cubiertas de asiento premium negro",
        imageSrc: "https://picsum.photos/seed/rs-p21/400/400",
        imageAlt: "Cubiertas de asiento",
        price: 145000,
        currencySymbol: "$",
      },
      {
        id: "22",
        title: "Ambientador clip ventilación vainilla",
        imageSrc: "https://picsum.photos/seed/rs-p22/400/400",
        imageAlt: "Ambientador",
        price: 12900,
        currencySymbol: "$",
      },
      {
        id: "23",
        title: "Gato hidráulico carrito 2 toneladas",
        imageSrc: "https://picsum.photos/seed/rs-p23/400/400",
        imageAlt: "Gato hidráulico",
        price: 198000,
        currencySymbol: "$",
      },
      {
        id: "24",
        title: 'Llave de cruz reforzada 17"–19"–21"–23"',
        imageSrc: "https://picsum.photos/seed/rs-p24/400/400",
        imageAlt: "Llave de cruz",
        price: 87500,
        currencySymbol: "$",
      },
    ],
  },
};
